# Generated by Django 3.2.11 on 2022-01-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipeingredients_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredients',
            name='quantity_as_float',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
