# Generated by Django 3.2.11 on 2022-02-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipeingredientsimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredientsimage',
            name='image',
            field=models.ImageField(upload_to='recipes/'),
        ),
    ]
