# Generated by Django 3.2.11 on 2022-02-12 18:33

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipeingredientsimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredientsimage',
            name='image',
            field=models.ImageField(upload_to=recipes.models.recipe_ingredient_image_upload_handler),
        ),
    ]
